# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_meshutils_module')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_meshutils_module')
    _meshutils_module = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_meshutils_module', [dirname(__file__)])
        except ImportError:
            import _meshutils_module
            return _meshutils_module
        if fp is not None:
            try:
                _mod = imp.load_module('_meshutils_module', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _meshutils_module = swig_import_helper()
    del swig_import_helper
else:
    import _meshutils_module
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def py_ProjectNozzleWall3D(MshNam, pyRefUp, pyRefDown, pyKnots_center, pyCoefs_center, pyKnots_r1, pyCoefs_r1, pyKnots_r2, pyCoefs_r2, OutNam):
    return _meshutils_module.py_ProjectNozzleWall3D(MshNam, pyRefUp, pyRefDown, pyKnots_center, pyCoefs_center, pyKnots_r1, pyCoefs_r1, pyKnots_r2, pyCoefs_r2, OutNam)
py_ProjectNozzleWall3D = _meshutils_module.py_ProjectNozzleWall3D

def py_ConvertGMFToSU2(MshNam, SolNam, OutNam):
    return _meshutils_module.py_ConvertGMFToSU2(MshNam, SolNam, OutNam)
py_ConvertGMFToSU2 = _meshutils_module.py_ConvertGMFToSU2

def py_ConvertSU2toGMSH(MshNam, SolNam, OutNam):
    return _meshutils_module.py_ConvertSU2toGMSH(MshNam, SolNam, OutNam)
py_ConvertSU2toGMSH = _meshutils_module.py_ConvertSU2toGMSH

def py_BSplineGeo3(pyknots, pycoefs, pyx, pyy, nx):
    return _meshutils_module.py_BSplineGeo3(pyknots, pycoefs, pyx, pyy, nx)
py_BSplineGeo3 = _meshutils_module.py_BSplineGeo3

def py_MeshPrepro2D(InpNam, OutNam):
    return _meshutils_module.py_MeshPrepro2D(InpNam, OutNam)
py_MeshPrepro2D = _meshutils_module.py_MeshPrepro2D

def py_BSplineGeo3LowF(pyknots, pycoefs, pyx, pyy, pydydx):
    return _meshutils_module.py_BSplineGeo3LowF(pyknots, pycoefs, pyx, pyy, pydydx)
py_BSplineGeo3LowF = _meshutils_module.py_BSplineGeo3LowF

def py_ExtractAlongLine(MshNam, SolNam, pyBox, pyResult, PyInfo, pyHeader):
    return _meshutils_module.py_ExtractAlongLine(MshNam, SolNam, pyBox, pyResult, PyInfo, pyHeader)
py_ExtractAlongLine = _meshutils_module.py_ExtractAlongLine

def py_ExtractAtRef(MshNam, SolNam, pyRefs, pyResult, PyInfo, pyHeader):
    return _meshutils_module.py_ExtractAtRef(MshNam, SolNam, pyRefs, pyResult, PyInfo, pyHeader)
py_ExtractAtRef = _meshutils_module.py_ExtractAtRef

def py_Extract_Vertices_Ref(MshNam, pyRefs, PyCrd_Out, PyVid_Out, PyRef_Tab):
    return _meshutils_module.py_Extract_Vertices_Ref(MshNam, pyRefs, PyCrd_Out, PyVid_Out, PyRef_Tab)
py_Extract_Vertices_Ref = _meshutils_module.py_Extract_Vertices_Ref

def py_ReadMesh(MshNam, SolNam, pyVer, pyTri, pyTet, pyEdg, pySol):
    return _meshutils_module.py_ReadMesh(MshNam, SolNam, pyVer, pyTri, pyTet, pyEdg, pySol)
py_ReadMesh = _meshutils_module.py_ReadMesh
# This file is compatible with both classic and new-style classes.


